"use client";
import React from "react";
import { motion } from "framer-motion";
import { AlertTriangle, Clock, Zap } from "lucide-react";
import { DashboardMode } from "@/lib/types";
import { getAIRecommendations } from "@/lib/intelligenceData";

const PRIORITY_STYLES: Record<string, { bg: string; border: string; text: string; icon: React.ReactNode }> = {
  critical: { bg: 'bg-red-500/8', border: 'border-red-500/20', text: 'text-red-400', icon: <AlertTriangle size={12} className="text-red-400" /> },
  high: { bg: 'bg-orange-500/8', border: 'border-orange-500/20', text: 'text-orange-400', icon: <Zap size={12} className="text-orange-400" /> },
  medium: { bg: 'bg-amber-500/8', border: 'border-amber-500/20', text: 'text-amber-400', icon: <Clock size={12} className="text-amber-400" /> },
};

export default function AIAdvisorTab({ mode }: { mode: DashboardMode }) {
  const recs = getAIRecommendations(mode);

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="bg-gradient-to-br from-primary-600/10 to-cyan-600/5 rounded-xl border border-primary-500/15 p-4">
        <div className="flex items-center gap-2 mb-2">
          <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-primary-500 to-cyan-500 flex items-center justify-center">
            <Zap size={14} className="text-white" />
          </div>
          <div>
            <h4 className="text-xs font-bold text-gray-200">AI Strategic Advisor</h4>
            <p className="text-[9px] text-gray-500">GeoAI-powered decision support</p>
          </div>
        </div>
        <p className="text-[10px] text-gray-400 leading-relaxed">
          Analysis of current spatial data reveals <span className="text-primary-400 font-semibold">{recs.filter(r => r.priority === 'critical').length} critical</span> and <span className="text-orange-400 font-semibold">{recs.filter(r => r.priority === 'high').length} high-priority</span> actions requiring immediate attention.
        </p>
      </div>

      {/* Recommendations */}
      <div className="space-y-2.5">
        {recs.map((rec, i) => {
          const style = PRIORITY_STYLES[rec.priority] || PRIORITY_STYLES.medium;
          return (
            <motion.div key={i} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.08 }}
              className={`${style.bg} border ${style.border} rounded-xl p-3.5 hover:scale-[1.005] transition-transform`}>
              <div className="flex items-start gap-2 mb-2">
                <div className="mt-0.5 shrink-0">{style.icon}</div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <span className={`text-[8px] font-black uppercase tracking-widest px-1.5 py-0.5 rounded-full ${style.bg} ${style.text} border ${style.border}`}>
                      {rec.priority}
                    </span>
                    <span className="text-[8px] text-gray-600 font-mono">{rec.timeline}</span>
                  </div>
                  <h5 className="text-[11px] font-bold text-gray-200 leading-tight">{rec.title}</h5>
                </div>
              </div>
              <p className="text-[10px] text-gray-400 leading-relaxed ml-5">{rec.description}</p>
              <div className="mt-2 ml-5 flex items-center gap-1.5 bg-black/20 rounded-lg px-2.5 py-1.5 border border-white/5">
                <span className="text-[8px] text-gray-500 uppercase tracking-wider font-semibold">Impact:</span>
                <span className="text-[9px] text-emerald-400 font-medium">{rec.impact}</span>
              </div>
            </motion.div>
          );
        })}
      </div>

      {/* Disclaimer */}
      <div className="bg-black/20 rounded-xl border border-white/5 p-3">
        <p className="text-[8px] text-gray-600 leading-relaxed text-center">
          Recommendations generated by spatial analysis engine using PostGIS risk models, exposure calculations, and multi-criteria decision analysis (MCDA). Subject to field verification.
        </p>
      </div>
    </div>
  );
}
