"""Initial PostGIS tables

Revision ID: df812fa1d401
Revises: None
Create Date: 2026-05-28 00:18:22.321996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'df812fa1d401'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable the PostGIS spatial engine extension in the database
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_history_id'), 'ai_chat_history', ['id'], unique=False)
    op.create_table('analytics_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_history_id'), 'analytics_history', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_history_location_name'), 'analytics_history', ['location_name'], unique=False)
    op.create_table('flood_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('inundation_depth', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_flood_zones_geom', 'flood_zones', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_flood_zones_id'), 'flood_zones', ['id'], unique=False)
    op.create_table('infrastructure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_infrastructure_geom', 'infrastructure', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_infrastructure_id'), 'infrastructure', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructure_name'), 'infrastructure', ['name'], unique=False)
    op.create_index(op.f('ix_infrastructure_type'), 'infrastructure', ['type'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('rainfall_intensity', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=False),
    sa.Column('land_use', sa.String(), nullable=False),
    sa.Column('calculated_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('uploaded_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('features_count', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='GEOMETRYCOLLECTION', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_uploaded_datasets_geom', 'uploaded_datasets', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_uploaded_datasets_id'), 'uploaded_datasets', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_uploaded_datasets_id'), table_name='uploaded_datasets')
    # op.drop_index('idx_uploaded_datasets_geom', table_name='uploaded_datasets', postgresql_using='gist')
    op.drop_table('uploaded_datasets')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_infrastructure_type'), table_name='infrastructure')
    op.drop_index(op.f('ix_infrastructure_name'), table_name='infrastructure')
    op.drop_index(op.f('ix_infrastructure_id'), table_name='infrastructure')
    # op.drop_index('idx_infrastructure_geom', table_name='infrastructure', postgresql_using='gist')
    op.drop_table('infrastructure')
    op.drop_index(op.f('ix_flood_zones_id'), table_name='flood_zones')
    # op.drop_index('idx_flood_zones_geom', table_name='flood_zones', postgresql_using='gist')
    op.drop_table('flood_zones')
    op.drop_index(op.f('ix_analytics_history_location_name'), table_name='analytics_history')
    op.drop_index(op.f('ix_analytics_history_id'), table_name='analytics_history')
    op.drop_table('analytics_history')
    op.drop_index(op.f('ix_ai_chat_history_id'), table_name='ai_chat_history')
    op.drop_table('ai_chat_history')
    # ### end Alembic commands ###
